apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videomatt-videos-mongo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.1.2
    helm:
      releaseName: videomatt-videos-mongo
      values: |-
        architecture: standalone
        auth:
          enabled: true
          rootUser: videomatt
          rootPassword: password
        image:
          registry: ghcr.io
          repository: dlavrenuek/bitnami-mongodb-arm
          tag: 6.0.6
          pullPolicy: IfNotPresent
        persistence:
          enabled: true
          size: 1Gi
        podAnnotations:
          linkerd.io/inject: "disabled"
        service:
          type: ClusterIP
          port: 27017
  destination:
    server: https://kubernetes.default.svc
    namespace: vittospace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
