apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videomatt-videos-postgres
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 13.2.30
    helm:
      releaseName: videomatt-videos-postgres
      values: |-
        image:
          repository: bitnami/postgresql
          tag: 17.5.0-debian-12-r7

        architecture: replication

        auth:
          database: videos
          username: videomatt
          password: password
          postgresPassword: password
          replicationUsername: videomattrep
          replicationPassword: password
          usePasswordFiles: false

        primary:
          persistence:
            enabled: true
          persistentVolumeClaimRetentionPolicy:
            whenDeleted: Delete
            whenScaled: Retain

        readReplicas:
          replicaCount: 1
          persistence:
            enabled: true
          persistentVolumeClaimRetentionPolicy:
            whenDeleted: Delete
            whenScaled: Delete

        volumePermissions:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vittospace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
