apiVersion: v1
kind: Service
metadata:
  name: videomatt-localstack
  namespace: vittospace
spec:
  type: NodePort
  selector:
    app: videomatt-localstack
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
      nodePort: 31566
