apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: vittospace
spec:
  encryptedData:
    .dockerconfigjson: AgBRGeoOT518nkFELQlipdanFPJ52GUZkRC7ErMp2zdgS5pljuhqO2g5CPA5olkIJydcLs6zSW7qPUChIp3zhRUpng+nQbOfQlwKy3p6qd60E9RvoxevKLygalcBr+9WfKFYTHQC20+215sCoB1KMxQvfV7iMqs6I9++uU7O6l2bidE427Qo5SHfn3QVCMA2FYFMUwbJUvpc19cXi1cXXB2IIK7BPuw5v6ht7Fh4QINJcAumdQZk6fkAUlY7N7kHC/HodJ2tbjwWyWZ02Hny67FTmfKl1L6L1AoTxbE83k8F1Gl2hZX5ghex34exSPJ0Qv1r//8wOalTHRjbvmDFdbWr37DlEcD16ARa++NqGwFKHRhWT3JYtCuLSp74JDzYajje7zQet95H6Q6GtPfMmJYROwxNGBLFbZ1wG8ywuLlIxErX9cZ9QAhAdXzCtPCp3y6Ai/n1PtF3YO9AJG3RBx+N9Bljyp8pnycyZ5NqXYk6+C31cd6jo8v8W9DkHhzaFa4144l5tpKDVdkrap6qkc81Vn5LfNc8YUQbIIbZqsrq4emEtgfdtt1VKTbyCKbgXrVo/4ouDmbQzIRk42Y24/U26ZwRw1iafFEALGslMlovAcVxHxeRGe2IAVUk/bOwcn1BLCLyVyvXnMx5ZWg+m+Z5eR4sxVljSqyKSlzBAbR/Jx950bhFx+2KrD05LrKsg3wXB5VH7aQiO/gKLTCK3UKXfJv+e9FwIZQwa5CNRyKTKnCfZv1DBZHYAodmHKA7T8zjmN5Qcn+UbVfTV/U5T4cGR7cbTp050yZtRXn829HY1kHtt2s7l2jnjvIyDizUK2KtrCJNcPA5T7zNenWviEIISdJF0gs9XB14cUWnLPvVDV1LYCPDXChrnrJ6OdTSLfxHMziuprWPw0mJljiqdtprWL7Bn5UHb2uNMJARwiwpvd64pqODObGinwKwyVzKJ6qfiWl2GoYq9dVjGZ+lnn8E5RLYld5xb8fDfg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: vittospace
    type: kubernetes.io/dockerconfigjson
