apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vittomatt-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vittomatt.github.io/rpi-charts/
    chart: vittomatt
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - Force=true
