apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vittomatt-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vittomatt.github.io/rpi-charts/
    chart: vittomatt
    targetRevision: 20250414-1600-2eeae27
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
