apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  encryptedData:
    ca.crt: AgBsVSVksD9Nj5paVXls68Lv//ym4ay8jZcAB3aOzIJsolMUxqOEx54HQvxBNL8/7n3ZEcGXLRBz40aUf8wc+wUfENpQf4LzHsYkcLYiIJbDryXJHzYKg/0iPZ4oL7E8RkYEM0dyBDJ3LoJmKhAv377UMg3CTsRVHhL6aaP7aAOVY0h6QUg0limkNMxf7eVmNgyCp+PZhSIVVHN+CUXk5H33WWt5rwNcHQzy3e6i+2OqjOHikIh+yxYY2SMcA06tuE46rFby4mi3nAStSyZqbyq4ffdXMYAz426Ps9MLEZzL6tyd8xb/OcUs8bjbAWEOjFn++zLZu4nMfLch5sgNrLUrDJAcO+p61JliDcwSxcMeaC+XV0MLB/xmOYWjb1ajff4OHbfkkUDDhrdaCwww5N+QR7usoTze2Um1tFu3X8dIOKFENeZzqVM6b0y/zDwZLDz8GyhUM0IWVLejAJFoVMfe6w2ZQnE+VBPbzhtdz04CnBM/wFpJfx41X1nP9+v4h+P6pfcz0OQa87694nFtE/W4r6y7dnaVDRta2v5xY3r6zxxF2Pc9pztyfSSxfiwl4g2837xGy/D0+8ICKDAyd6mhQ/VI/chxJ9hr7WP+Ef5Oka83jrrnA9MAqUUBmWi7E9xypjM6lqO2lCdSu+9N+4M/Hb3J9+BDX9kJ4taWdQio3FjqHeaYHTz+6NBL2d0nEvCNyeu0WZZ+gwWy7scD75YPADTqWbylG/CTvpum7oHHAxmdn5CDYQ5N9k4orIIOk3vBxTBDnrft80ePCyibVkLJNiwsIZ2G/9eNeEiRs/L/v6hg1lCzP+xRU43TWegBXBWL7vYOXXD9hjbSfBaZDETIMruCQmH3go0znswUC7ZkMHfRcio6YXv+5gI9EkaTAM3H3wQ6K6hQ+LORYabunTb+RabI3LeOgDadTad4h+jr/7VjZzZ65XoOigOArA20rzTJKo5KkC8rXTjseUKhrVkWO0Kx5tRlZjl2M9WVLyGW+2XpSzCnXkSRXjwbT3ceB/r7c0/Logy89uoR/0YIdGyFnAShy2aZBRRnAji20JVGmMHDJTssoOCzSIL3yPfRFxASoYqfox30NXeJeTEWKbqX0W40bI4+ztXMz+tufOMU92xdj0k+T82u78Ws8LCfKUO+4itUvxE6IIKDE0t+ZkB7N6LlVcJT7y/fobtdJ8EFlmuuF9+4YCE1YU2EqNnV+p6E/1aPKLAZF9glp9pEXvQt4qo+JXJ50a5KTJqZfKcI7lkDP/yw2LflmgdMZXphh97eXCeP8J8n21/GyGwTgre9zInzf/24rBvy1v3cum4oGDqAEyRETfwGAoIls/ZtDcRXEU/z0rtAK/1hno/A2LsOCEinCDgZ4bSb7oS/QQCml8N7CfVq5H5fpSWpF+ccNi7BYZLv6hwVNUwlT/hTJ0CYQsemgqeU4+3GCLoKj9uhcBJSwSOIvCjTWczp1XKE6ufSP7O9sbTCWZgv5oJmy/2Mf5/q5rnOsf4NRr3RMPwgbAJwAx3+miHuCCiKV1cTAzBS2G+lOcgYuG/cxQ==
  template:
    metadata:
      creationTimestamp: null
      name: linkerd-trust-anchor
      namespace: linkerd
    type: Opaque
