apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vittomatt-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vittomatt.github.io/rpi-charts
    chart: vittomatt
    # Auto updated by ci
    targetRevision: 20250518-1653-0c475eb
  destination:
    server: https://kubernetes.default.svc
    namespace: vittospace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
