apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videomatt-users-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vittomatt.github.io/rpi-charts
    chart: videomatt-users
    # Auto updated by ci
    targetRevision: 20250525-0033-b58ef06
  destination:
    server: https://kubernetes.default.svc
    namespace: vittospace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
