apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videomatt-videos-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 13.2.25
    helm:
      releaseName: postgres-videos
      values: |-
        image:
          repository: bitnami/postgresql
          tag: 15.7.0-debian-12-r12
          debug: true

        auth:
          username: videomatt
          password: password
          database: videos
          replicationUsername: videomatt
          replicationPassword: password

        architecture: replication

        primary:
          service:
            ports:
              postgresql: 5432
          persistence:
            enabled: true
            size: 1Gi
            storageClass: ""
          podAnnotations:
            linkerd.io/inject: "disabled"

        readReplicas:
          replicaCount: 1
          podAnnotations:
            linkerd.io/inject: "disabled"
          persistence:
            enabled: true
            size: 1Gi
            storageClass: ""

        volumePermissions:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vittospace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
