apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: linkerd-viz
spec:
  encryptedData:
    admin-password: AgB71/KjMnwUVsVFdL88QVeuTLUc9MKQLvz/vBubCkjy5s6GK0PzySngI3Ygki0YDUfV97UFMiF0X8GGsTARV6U9qcFZZjK/FuPZtnpOvjyBAdecvSzmk0qjxTzgYZRL9C/uMCE1dOpaaQ/v134s7tE/yNpto3wpropuZWXyqIrg8aHEEqiPSF9c+sfRS98rPxW0OT/jqlViJddcMA46JOb3Sso3xx8geDDs1QJjdKrayzv5h71RQMQ5SjdIFE18+FlpyYU6BgIWYvwhwYgzIwKc4ifhKzg3QcqjY4GafkqfxPlrTgGKo84DkHhd4GnAKKQ8s8gLu1p3Z6s3lfykGM3lquk+RE3kqD51k3b4HvT1F+1NoGYKxSYB3wgOu6sOKuL25SEIDXZxA516pQ7toGwZGf3PFvNcCJllb2fR2I4bM4U02P0A4zATWmcTp/32owAtbBbnKB5lqo6F1X8N4vbHSe1qAh3VOdkRp59N+MQC0pKbrB7GGIMel294vZyrD5ELvZ6I9HAL8apK3esL2favaUsiXvHkdM08oztuSIqNPJAzUkE1nk6ZdMHx1thpRL1OLNMXTrcPVUENeLDFb273E5Z36AQUpBecmr/E74VL2mghB32iIJhBr8i4Z5IOWkmxLCed1yXg4wWlPrsuk/mbVHjtEZCXanIlyVEFIuoL2ye2hdfbgq+CNdI9SQWwEU9wSkrCkw==
    admin-user: AgBu9TkV7Tld7RMjB737Ga1V31CTuiN9YmaepUiu3q9zkkjlHNIwvutvM7YV2nB6K2jfiDO/b18aX05oYABh7PgbEb2UbxS6lhh6kuRYuaUtDMVpEHuf8ViC3+01T+L8pYJKcrw07iD5P5iqpXZl/HvRvkPRFqCHddlIVCWKfWZsankG5hqoR4h9ARBDa0f4nvb2qYTWocM8FruaW9ka2yfGErkPjaw7ruXR9UScMiGZyo9h4au6gt6ziJ91K6iHO2v+SOAjdCh3lZhyvXFKv2tFQlTY/PJcLskfTP1bT8amvYXaVSUDVh6rPdYQh/oFugAYz5kOpft1qMKgJ3W2JPbd19XaUa68NU8LYcBrOOCwUFqAjFI9aqZv9LeP1sc8FJjHfQm/PC8Zj1UrvOxOQS1iaZz/4NqOj7/p4K5S4UWOudY2uKjx+j0YH6xqrCwp5TlnfhgMdBXEOYSqrsJMAfqiBiCKtAb5yRPha9foDkM+LsKeF91dIwvHCrEfQYrJWfwqmq3K1GcHvv0ny6+OEm6GJ8djU3ZBILGuDcWOWeeNegdPg6sVwwfJCU5aibkNwiXtu9jwt6U3FhkUcPO6+kgWaUeQqgRv09vGzasYl9lApmhdXnpNoCsu1aua7xZKXBAieCTqqAv5G78WE07Tsx2rDUP1YbJczkRexvCrvhHiPE9fF0DeQcg/TsVOGq6ABEE+5EC97Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: linkerd-viz
    type: Opaque
