---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgBWpXSy0ieECkBCMTJnSQenZF++ffzpBdAxQaKJ1ayc8Nt8lfGTX6INIzodbGTRAEvGCbWCSs5fRqZ/Pme8514j6T3DTGDgVgHoT4YqYVddGcStOdj1AutEBnLnmd/zUJscQdE4mI5Lc5wYWK2Uz0k0W8u12/OTwZ+CppQtpV0omUnGTaeKQm958ug7kIcFQgt8laihMkVpj8oiE4qzxuMivE4xFcvoXaotVWX9EAXhDU3GDq62PgOBK4u3nRnzqCPtZeXjaCcyYTGL5pKrC1UeI9BIbzhgx2/fsSUnnjZ0Xoym00mJ1zYav/8km3MIUALpzXPANN55uRza0yNIDClB+BB5f0+tixjxGCCR9AGSsAGcwpNuJV8arC/PGGhS3QrpH0Tr5b4ODYntgnbajcqS/iASqVLzcr/MNC+eVfjV4kqhlRvEmiNyKiRwnS3/tRbUCSb88MjVLBrvg+S5NemrBW0Lr5gPfurzT4h8r0sJ7HeLlXfa8GktZBt90gnSW0LyxxHCbGcWgGW1MtbZ1TJ5h18lttCWd0OEM4vJYNAtSbpCiBx+ReDnhnPZz/NeKl6CIWbMcX09ODKYi9rPZWCkdc+vxYGuW9Qysad/1OpZOtgDzf5u0CqKN+e67v6aOS7iHLGFaB8wIbwdxxHdPfMUIiDsnbvL/vhmPYbM04y1j7M5xyQxBq+nFkImNdWVr1ZSuZ0givknAjmMUyRyle6nkBGQ9ELBb8DkvhPXWUneEw==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
