---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgA50WJbr6xhB4sdlT/4Fk0byvLE0eA/RPGiChvkg29iUJC5jOa8WD5aQAcIg4pv3Fkb9NOsiqVo562TVCxUpAtVbiAqO5w670d9W/rKZrzRMrRedSIYPv3gfUIp6eyshicdfD/xQiJOe6lLjiyeu7mrZIcVYxrGo853rJvQI1nnYB+t5MNpqjX3dKYAsIwZEM3J2MT0C0PMEV/3Uk13xxqk2aAwTAFPiMeMJjywb9y2htpinj1fmMMe+oxq0Rz42e9HbWv5luctAGf5I4YxZurfdg6vDc/6lyJj3qyp5s1nGqx7eHdIQDpJx5iTq0O8TeS2GkoRKAAuVGokoc7iqX8yMCLwsHg37ntChLlgc18Lrl8zNrP4tKZ9SA2U4vdxbEd16Tr8nuSZ9a3TtPhmRMMZReAkH5cg2IoOsl9E0tZNf4OH+ApNVJbFEY+BgS707pw/gMdKAsLdvGfDZrpSfa01XlCa+LMmY9OjILNwOVB3cXevXXbnzl1BXrWgdeKZiW1k6J7QSJlxcwvj4vYU1kbgwPtXF7OMz18Rqp+YFYHABmGElTnQMYXGpfJZKoW1Dfy0dVhjj2AZNlJKH9r6Z6za/8SVbGjeFrC/zjshD21CptEs9C5cueGpz12Js21QhVPS+X3JjvXbedX1pUiBVaCcSVp1KT2d4Afh7b9WdhRTMga4CoZqRF7ht2xgTq/S7gQ=
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
