---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datadog-secret
  namespace: vittospace
spec:
  encryptedData:
    api-key: AgAfSLigYwWaalMq/tWQDQhC9J4pPCA3WB8l1Y2v7FLewaqeYXqcW43z8RwJ7qjuMf8qeGVNLVwTkWNUrRRB3x1ejOcYw8J+k0dwtuqK/ebKeSGRf+vlJIdYSgq1mR71Qi7eBNLSO8fWTXV2No+5P5mCnSCdzCuQyV1kbm5eJIuUpcKEJTaaTWeqinWiHrmxywrpN9euPdsUaD0QCradMeUhJ5DhEMNE2J7JNAGRtVAM1gtLoxUKROlrIe+llSAw1KZjOzdrBtveB8wbv+nTrt03T6gEJU9499RL1uL5hhwcVEtq3Li5vBHod3peKORPpGrg9olvHK/liOB/ELCnmpLEJZ1o9DPjyr/u6/ad4oOQVEas2qP6C3/wGRwveJHMbTpfi81SrZFgyAgnfad20Kxi4ArHi2Sdvyw68D8TsK5nIvl+B30MZg6TOOqRRio3FkQ9NCpQPuTEiN8sty4mlHcuE3haY6+5/IgUYfkO4dh5p4kGxCtIP5nncITXLuFXPIta00qkDq610wY0zobEZxWx/IqX7RSR4TSy4tne/YIsUDdpf9askdkMeYLByjQZJpIGDANoCwRRdWmk4hceYYvH8zBwFJgfs2u31K8OfQGU720gm+3+GBgVe735F/x4yblEfY2s5D11hw8YTGx4sYY0noiXnHPBmfCff7xEkt3l0Zqaq4khNo9MMg6uzHqwYab8RqJN1M0Vdnf3dczf+r55kRBIge7ESau1ViMscE/CJg==
  template:
    metadata:
      name: datadog-secret
      namespace: vittospace
