apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prode-postgres
  namespace: vittospace
spec:
  serviceName: prode-postgres-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: prode-postgres
  template:
    metadata:
      labels:
        app: prode-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prode-secret
                  key: PRODE_POSTGRES_DB_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
