apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: "https://github.com/vittomatt/rpi-charts"
    targetRevision: HEAD
    path: secrets/linkerd
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
