apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/edge
    chart: linkerd-viz
    targetRevision: 2025.4.4
    helm:
      values: |
        dashboard:
          enforcedHostRegexp: ".*"
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
