apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vittomatt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vittomatt.github.io/rpi-charts
    chart: vittomatt
    # Auto updatede by ci
    targetRevision: 20250425-1540-fa3ed09
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
