apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prode-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vittomatt.github.io/rpi-charts
    chart: prode
    # Auto updated by ci
    targetRevision: 20250613-0147-47eb2a6
  destination:
    server: https://kubernetes.default.svc
    namespace: vittospace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
