apiVersion: v1
kind: Service
metadata:
  name: videomatt-videos-mongo
  namespace: vittospace
spec:
  type: ClusterIP
  selector: { app: mongo }
  ports:
    - port: 27017
      targetPort: mongo
      name: mongo
